c_stdlib_version:          # [osx and x86_64]
  - '10.15'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '11.0'                 # [osx and x86_64]

c_compiler_version:        # [osx]
  - 15                     # [osx]
cxx_compiler_version:      # [osx]
  - 15                     # [osx]
build_variant:
  - "qt6"
  - "qt5"
qt6_main:
- '6.7'