MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.15'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '11.0'                 # [osx and x86_64]

c_compiler_version:        # [osx]
  - 15                     # [osx]
cxx_compiler_version:      # [osx]
  - 15                     # [osx]
qt-main:
  - "qt6-main"
  - "qt-main"