{% set name = "soqt" %}

{% set version = "1.6.0" %}
{% set commitsoanydata = "3ff6e9203fbb0cc08a2bdf209212b7ef4d78a1f2" %}
{% set commitsogui = "80e75695974e20340853084c858e4a70c2411efb" %}

{% set sha256soqt = "80bbee01089af754380c48ea435008ea93465149999a545741c410efe8e9bef9" %}
{% set sha256soanydata = "ede29d60d1b35e66193aaf115784f87867ab1658cb1d977fe75dfc0d0ffb3241" %}
{% set sha256sogui = "f14938ed9ed9920feac25273c6499be131fb55fab454747449ee9ad3e98cd765" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    - url: https://github.com/coin3d/soqt/archive/SoQt-{{ version }}.tar.gz
      sha256: {{ sha256soqt }}
    - url: https://github.com/coin3d/soanydata/archive/{{ commitsoanydata }}.tar.gz
      sha256: {{ sha256soanydata }}
      folder: data
    - url: https://github.com/coin3d/soanydata/archive/{{ commitsogui }}.tar.gz
      sha256: {{ sha256sogui }}
      folder: src/Inventor/Qt/common


build:
    number: 0

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxfixes') }}  # [linux]
        - {{ cdt('libxcb') }}  # [linux]
        - {{ cdt('libxau') }}  # [linux]
        - {{ cdt('libxau') }}  # [linux]
        - {{ cdt('libXxf86vm') }}  # [linux]
        - ninja
        - cmake
    host:
        - qt
        - coin3d
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxi  # [linux]
    run:
        - qt
        - coin3d
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxi  # [linux]
test:
    requires:
        - cmake

    files:
        - CMakeLists.txt

    commands:
        - cmake .

about:
    home: https://bitbucket.org/Coin3D/soqt
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: SoQt library needed by Coin3d.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.
    doc_url: https://bitbucket.org/Coin3D/soqt
    dev_url: https://bitbucket.org/Coin3D/soqt

extra:
    recipe-maintainers:
        - looooo
