{% set name = "soqt" %}
{% set version = "1.6.0" %}
{% set sha256 = "8b54eb87312ddd7d7b9c54df6ebf0b78b0021c900019ad74b51f1402d882184a" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    - url: https://github.com/coin3d/soqt/archive/ab0595fe864470451ca303afb9b49c796daf2c00.tar.gz
      sha256: {{ sha256 }}
      patches:
        - gl_private_linking.patch  # [linux]


build:
    number: 3

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - ninja
        - cmake
    host:
        - qt6-main
        - coin3d
        
    run:
        - qt6-main
        - coin3d
test:
    requires:
        - cmake
        - ninja
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]

    files:
        - CMakeLists.txt

    commands:
        - cmake -G "Ninja" .

about:
    home: https://bitbucket.org/Coin3D/soqt
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: SoQt library needed by Coin3d.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.
    doc_url: https://bitbucket.org/Coin3D/soqt
    dev_url: https://bitbucket.org/Coin3D/soqt

extra:
    recipe-maintainers:
        - looooo
