{% set name = "soqt" %}
{% set version = "1.6.0a" %}
{% set commitsoqt = "ea5cd7646087" %}
{% set commitsoanydata = "f8721d842e1d" %}
{% set commitsogui = "04d1d8732971" %}
{% set commitcpack = "7a4972d58197" %}
{% set sha256soqt = "947e211ee744ea6aea4e04a0aaba87c54d0679ce34779e7907ef6f74e6ef64f0" %}
{% set sha256soanydata = "c319e7ccf537ea78298c1c1c3612c36a6671be2afabaa1e9ae21da0e36db348c" %}
{% set sha256sogui = "1ffcb62cd544cf34102ad927e5b414c7e377636d17960657ccea0452372cabba" %}
{% set sha256cpack = "1d4570153fd4bb92ce4cbf8eae413ba2bb810851a158e680706cc1cf7ff027e3" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    - url: https://bitbucket.org/Coin3D/soqt/get/{{ commitsoqt }}.zip
      sha256: {{ sha256soqt }}
    - url: https://bitbucket.org/Coin3D/soanydata/get/{{ commitsoanydata }}.zip
      sha256: {{ sha256soanydata }}
      folder: data
    - url: https://bitbucket.org/Coin3D/sogui/get/{{ commitsogui }}.zip
      sha256: {{ sha256sogui }}
      folder: src/Inventor/Qt/common
    - url: https://bitbucket.org/Coin3D/cpack.d/get/{{ commitcpack }}.zip
      sha256: {{ sha256cpack}}
      folder: cpack.d


build:
    number: 1000

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
    host:
        - qt 5.*
        - coin3d
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxi  # [linux]
    run:
        - qt 5.*
        - coin3d
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxi  # [linux]
test:
    requires:
        - cmake

    files:
        - CMakeLists.txt

    commands:
        - cmake .

about:
    home: https://bitbucket.org/Coin3D/soqt
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: SoQt library needed by Coin3d.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.
    doc_url: https://bitbucket.org/Coin3D/soqt
    dev_url: https://bitbucket.org/Coin3D/soqt

extra:
    recipe-maintainers:
        - looooo
