appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vVeRRwnb/3CBRcxYHStMZWAbBRVlpigIYPGCBJKg0dxOt3dPhpI4vosy/nGLq/L6ZnPoLsaCvz2ezhpvc33n4bz9RYAs0EcyORPYF2XPEUXSLsERURcvIZGbmLeeWamRPLl5u3HtZwqyGlbZEhP7foHD3OWXfWr3OvsCazS2+DAvmHado32WSNRWJqwcjkdHuf4xRy7hS3o9YSfes4bYheO6boDX/oOWbnbWAnOBG6Y9A4VTvszUSWtEaNEvAqeR44tmv17QC4CaEBZdu3ChCs7uG3o+8twLVOFQoeVgcQ/7qUGGRST0Dttf3/m4D3H5kRNQk+jAsxyiXpwwx8F+MOxH9u7m6rre6Fpt1uXUoiQQqF8doWMKv0cgsIBUxXzcA9BeRqj+k65bxg6sugDQ0ODCm73MiOlE8DbC6k+aMKTBFGsbzQpLb7nSltXTtjR6r0QJfK0rxBSNVSOBbdlE7CY5YcajkuZU650m5lHMao2vK9Dw1dn6E8/5LG367c8zQcfLlASEBIOQfdEO+dANkgjAsO4ym8v3HkMY3CY2ALB9IVFFC2EIdUty3Z4grMMnWJQCnBH5UcGuij3L/yuTVSsZJPiBZXK2iQPvNqCjlNThUFeqr/XE7ZO6wKDUFSkFPhlhr7/H20k62T46bBxNTezl9JSHO5XNqBx5R8q7IG0=}
